name = "ldc-shop-v2"
main = "worker.js"
compatibility_date = "2026-01-06"

# Custom Domain
routes = [
	{ pattern = "shop.example.com", custom_domain = true }
]

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "ldc-shop-db"
database_id = "YOUR_DATABASE_ID"
# preview_database_id = "DB" # Use strictly for local dev

[triggers]
crons = ["*/1 * * * *"]
